version: "3.9"

services:
    mysql:
        hostname: mysql
        image: mysql:latest
        ports:
            - ${DB_PORT}:3306
        environment:
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - MYSQL_DATABASE=${DB_DATABASE}

